'use strict';
const C=window.JH, $=s=>document.querySelector(s), esc=C.escape;
const KEY='jh-planning-v1';
let projects=[],activeId=null,step=0,saveError=false,loadError=false,timer;
try{const raw=localStorage.getItem(KEY);if(raw)projects=C.parseBackup(raw);}catch(e){loadError=true;}
const now=()=>new Date().toLocaleString('ko-KR',{timeZone:'Asia/Seoul'});
const current=()=>projects.find(p=>p.id===activeId);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function persist(){if(loadError){saveError=true;$('#save-status').textContent='기존 자료 읽기 오류 · 백업 필요';return false;}try{localStorage.setItem(KEY,JSON.stringify({format:KEY,projects}));saveError=false;$('#save-status').textContent='이 브라우저에 저장됨';return true;}catch(e){saveError=true;$('#save-status').textContent='저장 실패 · 파일로 백업해 주세요';toast('저장 공간을 확인해 주세요. 현재 내용은 전체 기록 백업으로 보존할 수 있습니다.');return false;}}
function updateSidebar(){const p=current();$('#home-button').classList.toggle('active',!p);$('#side-list').innerHTML=projects.map(x=>'<button class="side-project '+(x.id===activeId?'active':'')+'" data-open="'+esc(x.id)+'">'+esc(x.name||'이름 없는 프로젝트')+'</button>').join('');$('#breadcrumb').textContent=p?'작업실 / '+(p.name||'이름 없는 프로젝트'):'작업실 / 내 프로젝트';}
function home(){activeId=null;updateSidebar();$('#main').innerHTML=`
  <section class="hero"><div><div class="eyebrow">JH PLANNING STUDIO</div><h1>좋은 기획은<br><em>이유</em>에서 시작합니다.</h1><p>무엇을 왜 해야 할까요?<br>흩어진 생각을 문제, 지표, 실행 문서로 연결해<br>설명할 수 있는 기획을 만드세요.</p><button class="button primary" data-action="new">내 프로젝트 기획하기 <span>→</span></button><p class="hero-note">산업을 제한하지 않습니다. 여러분의 상황부터 시작하세요.</p></div><div class="method-card"><h2>생각에서 실행까지, 세 가지 기준</h2><div class="method-row"><span class="method-num">01</span><div><strong>문제를 분명하게</strong><p>누구의 어떤 문제를, 왜 해결하나요?</p></div></div><div class="method-row"><span class="method-num">02</span><div><strong>성공을 구체적으로</strong><p>어떤 변화가 생기면 잘한 걸까요?</p></div></div><div class="method-row"><span class="method-num">03</span><div><strong>판단을 문서로</strong><p>선택과 이유를 실행 가능한 문서로 남깁니다.</p></div></div></div></section>
  <section><div class="section-title"><h2>내 프로젝트 <span>${projects.length}</span></h2><span>작성 중인 기획과 확정한 문서</span></div><div class="projects">${projects.length?projects.map(p=>{const n=C.issues(p).length;return `<button class="project-card" data-open="${esc(p.id)}"><span class="badge ${p.example?'example':''}">${p.example?'가상 예시':'내 기획'}</span><h3>${esc(p.name||'이름 없는 프로젝트')}</h3><p>${esc(p.goal||'문제를 정의하고 첫 방향을 정해 보세요.')}</p><div class="card-meta"><span>${esc(p.industry||'산업 미지정')} · ${p.revisions.length?'확정 문서 '+p.revisions.length+'개':'작성 중'}</span><span>${n?'확인 '+n+'건':'필수 입력 완료'} →</span></div></button>`}).join(''):'<div class="empty-state"><div><h3>첫 기획을 시작해 볼까요?</h3><p>새 프로젝트를 만들거나, 아래 가상 예시로 결과물을 먼저 확인하세요.</p></div><button class="button" data-action="new">새 프로젝트 ＋</button></div>'}</div></section>
  <section><div class="section-title"><h2>다른 산업, 같은 기획의 시작</h2><span>모든 내용·수치는 가상 예시입니다</span></div><div class="examples">${examples.map((x,i)=>`<button class="example-card" data-example="${i}"><span class="badge example">${esc(x.industry)} · 가상</span><h3>${esc(x.name)}</h3><p>${esc(x.summary)}</p><span class="arrow">예시 기획 열기 ↗</span></button>`).join('')}</div></section>`;
  if(loadError){$('#main').insertAdjacentHTML('afterbegin','<div class="errors">저장된 기록을 읽지 못했습니다. 원본은 보존하고 새 저장을 중단했습니다. 전체 기록 백업으로 원본을 내려받아 보관해 주세요.</div>');}
}
const hints={target:'사람과 상황을 함께 적어 주세요. 업종만으로 대상을 정하지 않습니다.',problem:'관찰한 불편과 그 원인에 대한 추측을 구분해 주세요.',importance:'이 문제로 어떤 행동이나 기회를 놓치고 있나요?',evidence:'직접 들은 말, 관찰한 행동, 자료 출처를 적습니다. 근거가 없으면 미확인이라고 적어 주세요.',assumption:'검증이 필요한 원인이나 기대를 적습니다.',goal:'조회수보다 문의·신청처럼 원하는 행동을 먼저 생각해 보세요.',reason:'다른 후보 대신 이 방향을 선택한 이유는 무엇인가요?',exclude:'범위를 지켜야 집중해서 실행할 수 있습니다.',message:'대상에게 약속할 가치와 그 근거를 담아 주세요.',action:'무엇을 만들고, 상대에게 어떤 행동을 요청할지 적어 주세요.',baseline:'아직 측정하지 않았다면 비워 두세요. 0과 미확인은 다릅니다.',definition:'예: 신청 완료 건수. 취소·중복 제외. 비율이면 분자와 분모를 적습니다.',source:'자료를 어디에서 누가 확인할지 적어 주세요.',rule:'예: 목표 미달이면 신청 과정의 막힘을 조사하고 안내를 수정한다.',revisionReason:'처음 확정한 이유 또는 이전 버전에서 바꾼 점과 이유를 적어 주세요.'};
const placeholders={target:'예: 첫 교육 프로그램을 찾는 직장인',problem:'지금 어떤 상황에서 무엇이 막히나요?',importance:'이 문제를 미뤄 두면 어떤 영향이 생기나요?',evidence:'확인한 내용과 출처 / 아직 없다면 미확인',assumption:'예: 시간 정보가 부족해 신청을 망설일 수 있다',goal:'예: 대상 고객이 프로그램을 이해하고 신청하도록 한다',reason:'이 후보가 목적과 제약에 맞는 이유',exclude:'예: 유료 광고 집행과 여러 채널 동시 운영',message:'대상에게 전달할 한 가지 핵심 가치',channel:'예: 소개 페이지, 이메일, 인스타그램',action:'예: 소개 페이지를 만들고 일정 확인 후 신청을 요청한다',metric:'예: 완료 신청 수',definition:'계산 방법과 포함·제외 기준',source:'예: 담당자가 확인하는 신청 기록',rule:'어떤 결과에서 유지·수정·중단할까요?',revisionReason:'예: 대상과 목적을 정리해 첫 실행 기준으로 확정'};
function field(key,wide=false){const p=current(),value=p[key],optional=['industry','assumption','exclude','baseline'].includes(key),textKeys=['target','problem','importance','evidence','assumption','goal','reason','exclude','message','action','definition','source','rule','revisionReason'];let control;
 if(key==='unit')control='<select id="f-unit" data-field="unit">'+['건','명','%','원','회','일'].map(v=>`<option ${p.unit===v?'selected':''}>${v}</option>`).join('')+'</select>';
 else if(textKeys.includes(key))control=`<textarea id="f-${key}" data-field="${key}" maxlength="10000" placeholder="${esc(placeholders[key]||'')}">${esc(value)}</textarea>`;
 else control=`<input id="f-${key}" data-field="${key}" ${['baseline','targetValue'].includes(key)?'type="number" min="0" step="any"':key==='start'||key==='end'?'type="date"':'type="text" maxlength="100"'} value="${esc(value)}" placeholder="${esc(placeholders[key]||'')}">`;
 return `<label class="${wide?'wide':''}" for="f-${key}">${C.fields[key]} <span class="${optional?'optional':'required'}">${optional?'선택':key==='unit'?'':'필수'}</span>${control}${hints[key]?'<span class="hint">'+hints[key]+'</span>':''}</label>`;
}
function problemPanel(){return '<div class="field-grid">'+field('name')+field('industry')+field('target',true)+field('problem',true)+field('importance',true)+field('evidence',true)+field('assumption',true)+field('goal',true)+'</div>';}
function strategyPanel(){const p=current();return '<div class="candidates">'+p.candidates.map((c,i)=>`<div class="candidate ${p.selected===String(i)?'selected':''}"><div class="candidate-title"><input type="radio" name="selected" id="pick-${i}" data-pick="${i}" ${p.selected===String(i)?'checked':''}><label for="pick-${i}">후보 ${i+1}${p.selected===String(i)?' · 선택한 방향':''}</label></div><div class="field-grid"><label>후보 ${i+1} 이름<input data-candidate="${i}" data-key="name" maxlength="10000" value="${esc(c.name)}" placeholder="어떤 방향인가요?"></label><label>후보 ${i+1} 근거·제약<input data-candidate="${i}" data-key="basis" maxlength="10000" value="${esc(c.basis)}" placeholder="필요한 자료, 작업량, 제약"></label><label class="wide">후보 ${i+1} 실행 내용<textarea data-candidate="${i}" data-key="action" maxlength="10000" placeholder="무엇을 실행할까요?">${esc(c.action)}</textarea></label></div></div>`).join('')+'</div><div class="field-grid decision">'+field('reason',true)+field('exclude',true)+field('message',true)+field('channel',true)+field('action',true)+'</div>';}
function metricPanel(){return '<div class="field-grid">'+field('metric')+field('unit')+field('baseline')+field('targetValue')+field('definition',true)+field('source',true)+field('start')+field('end')+field('rule',true)+'</div>';}
function docPanel(){const p=current();return field('revisionReason',true)+'<div class="report-actions"><button class="button accent" id="finalize">기획서 확정 · 버전 보존</button><button class="button" id="download-draft">초안 HTML 다운로드</button><button class="button" id="print">인쇄 / PDF 저장</button></div><div id="document-preview">'+C.report(p)+'</div><section class="revision-list"><h3>확정한 문서 '+p.revisions.length+'개</h3><p class="muted">확정본은 현재 입력을 수정해도 바뀌지 않습니다. 다운로드한 파일을 열어 이전 버전을 확인할 수 있습니다.</p>'+p.revisions.map(r=>`<div class="revision-item"><div><strong>v${String(r.version).padStart(2,'0')} · ${esc(r.date)}</strong><p>${esc(r.reason)}</p></div><button class="button" data-revision="${r.version}">v${String(r.version).padStart(2,'0')} 다운로드</button></div>`).join('')+'</section>';}
const titles=['누구의 어떤 문제인가요?','무엇을 왜 선택하나요?','잘했다는 기준을 정해 주세요.','판단을 하나의 문서로.'];
const intros=['관찰한 사실과 아직 모르는 것을 나누어, 출발점을 분명하게 만듭니다.','실행 후보를 비교하고, 선택한 이유를 남깁니다. 모든 후보를 채울 필요는 없습니다.','성과를 예측하기보다, 실행 후 무엇을 확인할지 정합니다.','필수 입력을 확인하고 기획서를 확정하세요. 실제 실행·효과와는 별개입니다.'];
function workspace(){const p=current();if(!p)return home();updateSidebar();$('#main').innerHTML=`<div class="workspace-head"><div><span class="badge ${p.example?'example':''}">${p.example?'가상 예시 · 실제 고객·성과 아님':'내 기획 프로젝트'}</span><h1>${esc(p.name||'이름 없는 프로젝트')}</h1><p>${esc(p.industry||'산업 미지정')} · ${p.revisions.length?'확정본 '+p.revisions.length+'개 보존':'아직 확정 전'} · 언제든 수정할 수 있습니다</p></div><button class="button" id="back-home">← 프로젝트 목록</button></div><nav class="steps" aria-label="기획 단계">${['문제 정의','방향과 선택','성공 지표','최종 문서'].map((t,i)=>`<button class="step ${i===step?'active':''}" data-step="${i}" ${i===step?'aria-current="step"':''}><span>0${i+1}</span>${t}</button>`).join('')}</nav><div class="work-grid"><section class="panel"><div class="eyebrow">STEP 0${step+1} / 04</div><h2>${titles[step]}</h2><p class="panel-intro">${intros[step]}</p><div id="validation"></div>${[problemPanel,strategyPanel,metricPanel,docPanel][step]()}<div class="panel-actions"><button class="button" ${step===0?'id="back-home-bottom"':'data-step="'+(step-1)+'"'}>← ${step===0?'프로젝트 목록':'이전 단계'}</button>${step<3?'<button class="button primary" data-step="'+(step+1)+'">'+['방향과 선택','성공 지표','최종 문서'][step]+' →</button>':'<span class="muted">초안과 확정본은 별도 보존</span>'}</div></section><aside class="aside-note"><div class="eyebrow">PLANNING NOTE</div><h3>무엇을 왜 해야 하나?</h3><p>기획의 중심은 결과물보다<br>그 결과물이 필요한 이유입니다.</p><ul><li>문제는 누구의 것인가요?</li><li>주장에는 근거가 있나요?</li><li>다른 선택지는 무엇인가요?</li><li>성공은 무엇으로 확인하나요?</li></ul><hr><div class="completion-row"><span>필수 입력·형식</span><strong id="completion"></strong></div><div class="progress-track"><div id="progress-bar"></div></div><p id="completion-note"></p><hr><p>여기는 기획을 작성하는 공간입니다. AI 생성이나 실제 성과 분석을 실행하지 않습니다.</p></aside></div>`;progress();}
function progress(){const p=current();if(!p)return;const errors=C.issues(p);const missing=new Set(errors.map(e=>e.key));const total=C.required.length+1,done=total-missing.size;if($('#completion'))$('#completion').textContent=done+' / '+total;if($('#progress-bar'))$('#progress-bar').style.width=Math.max(0,Math.min(100,done/total*100))+'%';if($('#completion-note'))$('#completion-note').textContent=errors.length?'확인할 항목 '+errors.length+'건. 형식 확인이며 기획의 타당성을 검증하는 것은 아닙니다.':'필수 입력과 형식을 확인했습니다. 기획의 타당성과 실제 효과는 별도 검토가 필요합니다.';}
function open(id){activeId=id;step=0;workspace();window.scrollTo(0,0);}
function newProject(name,industry,example=null){if(loadError){toast('기존 자료를 읽지 못해 새 저장을 중단했습니다. 먼저 원본 백업을 보존해 주세요.');return;}if(projects.length>=50){toast('최대 50개 프로젝트를 보관할 수 있습니다.');return;}const p=example?example():C.blank(name,industry);p.id=crypto.randomUUID();p.updated=now();projects.push(p);persist();open(p.id);}
function download(text,name,type='text/html;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function htmlFile(body){return '<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>JH 기획 · 기획서</title><style>body{font-family:Arial,"Malgun Gothic",sans-serif;color:#20313d;max-width:820px;padding:40px 24px;margin:auto;line-height:1.7}h2{font-size:28px}.eyebrow,.doc-meta{font-size:12px;color:#596975}.report-header{border-bottom:2px solid #172b3b;padding-bottom:24px}section{padding-top:24px;break-inside:avoid}h3{font-size:18px}dt{font-size:13px;color:#596975;font-weight:700;margin-top:16px}dd{margin:6px 0;white-space:pre-wrap;overflow-wrap:anywhere}.doc-notice{background:#f3f3ed;padding:20px;margin-top:24px;font-size:12px}</style></head><body>'+body+'</body></html>';}
function filename(p,suffix){return (p.name||'기획서').replace(/[<>:"/\\|?*\x00-\x1f]/g,'-').slice(0,70)+'-'+p.id.slice(0,8)+'-'+suffix+'.html';}
function finalize(){const p=current(),errors=C.issues(p);if(errors.length){$('#validation').innerHTML='<div class="errors" role="alert"><h3>확정 전에 '+errors.length+'개 항목을 확인해 주세요.</h3>'+errors.map(e=>'<button data-error="'+esc(e.key)+'">'+esc(e.message)+' →</button>').join('')+'</div>';$('#validation').scrollIntoView({block:'start',behavior:'smooth'});return;}if(p.revisions.length>=30){toast('한 프로젝트에 최대 30개 확정본을 보존합니다.');return;}const version=p.revisions.length+1;const snapshot=JSON.parse(JSON.stringify({...p,revisions:[]}));const revision={version,date:now(),reason:p.revisionReason,snapshot,html:C.report(snapshot,version)};p.revisions.push(revision);p.updated=now();if(!persist()){p.revisions.pop();toast('저장에 실패해 확정을 보류했습니다. 초안 다운로드 또는 백업으로 내용을 보존하세요.');return;}workspace();toast('확정본 v'+String(version).padStart(2,'0')+'을 보존했습니다. 실제 실행은 아직 확인 전입니다.');}
document.addEventListener('input',e=>{const p=current();if(!p)return;const el=e.target;if(el.dataset.field){p[el.dataset.field]=el.value;el.classList.remove('field-invalid');}else if(el.dataset.candidate){p.candidates[Number(el.dataset.candidate)][el.dataset.key]=el.value;}else return;p.updated=now();persist();progress();if(step===3)$('#document-preview').innerHTML=C.report(p);});
document.addEventListener('change',e=>{const p=current();if(!p)return;if(e.target.dataset.pick!==undefined){p.selected=e.target.dataset.pick;p.updated=now();persist();workspace();}else if(e.target.dataset.field==='unit'){p.unit=e.target.value;persist();progress();}});
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;
 if(el.dataset.action==='new'){$('#create-dialog').showModal();$('#new-name').focus();}
 else if(el.dataset.open)open(el.dataset.open);
 else if(el.dataset.example!==undefined)newProject('','',()=>examples[Number(el.dataset.example)].build());
 else if(el.dataset.step!==undefined){step=Number(el.dataset.step);workspace();window.scrollTo(0,0);}
 else if(el.dataset.error){const key=el.dataset.error;step=C.steps[key]??0;workspace();const input=key==='selected'?$('#pick-0'):$('#f-'+key);input?.classList.add('field-invalid');input?.focus();input?.scrollIntoView({block:'center'});}
 else if(el.dataset.revision){const p=current(),r=p.revisions.find(r=>r.version===Number(el.dataset.revision));download(htmlFile(r.html),filename(p,'v'+String(r.version).padStart(2,'0')));}
 else if(['home-link','home-button','back-home','back-home-bottom'].includes(el.id)){e.preventDefault();home();window.scrollTo(0,0);}
 else if(el.id==='cancel-create')$('#create-dialog').close();
 else if(el.id==='finalize')finalize();
 else if(el.id==='download-draft'){const p=current();download(htmlFile(C.report(p)),filename(p,'초안-'+Date.now()));toast('현재 입력으로 초안을 내려받았습니다.');}
 else if(el.id==='print')window.print();
 else if(['backup','backup-mobile'].includes(el.id)){let data;if(loadError){data=localStorage.getItem(KEY)||'';}else data=JSON.stringify({format:KEY,projects},null,2);download(data,'JH-기획-백업-'+Date.now()+'.json','application/json');toast(loadError?'읽지 못한 원본을 백업했습니다.':'현재 기획과 확정본을 백업했습니다.');}
 else if(['restore','restore-mobile'].includes(el.id))$('#restore-file').click();
});
$('#create-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#new-name').value.trim();if(!name){$('#new-name').focus();return;}newProject(name,$('#new-industry').value.trim());$('#create-dialog').close();$('#create-form').reset();});
$('#restore-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10000000)throw Error('백업 파일은 10MB 이하로 선택해 주세요.');if(loadError)throw Error('기존 저장 자료의 읽기 오류가 있어 복원을 중단했습니다. 원본 백업을 보존해 주세요.');const restored=C.parseBackup(await file.text()),ids=new Set(projects.map(p=>p.id)),added=restored.filter(p=>!ids.has(p.id));if(projects.length+added.length>50)throw Error('복원 후 프로젝트가 50개를 넘습니다.');const before=projects;projects=[...projects,...added];if(!persist()){projects=before;throw Error('저장 실패로 복원을 취소했습니다.');}home();toast(added.length+'개 추가, 기존 번호 '+(restored.length-added.length)+'개 보존했습니다.');}catch(err){toast('복원하지 못했습니다: '+err.message);}e.target.value='';});
function example(data){return Object.assign(C.blank(),{example:true,baseline:'',targetValue:'10',unit:'건',start:'2026-10-05',end:'2026-10-18',revisionReason:'가상 사례로 첫 기획의 문제·방향·확인 기준을 정리',...data});}
const examples=[
 {industry:'식음료',name:'로컬 커피 구독의 첫 홍보',summary:'가치를 모르는 고객에게, 어떤 이유로 구독을 제안할까요?',build:()=>example({name:'로컬 커피 구독의 첫 홍보',industry:'식음료',target:'집에서 커피를 마시며 원두 선택을 어려워하는 사람',problem:'구독 서비스의 구성과 선택 이유를 한눈에 알기 어렵다는 상황 가설',importance:'가격만 비교하면 서비스가 제공하는 선택의 도움을 전달하기 어렵다.',evidence:'가상 요청서: 원두 구성과 배송 일정 설명이 흩어져 있다고 설정. 실제 인터뷰는 미실시.',assumption:'취향별 구성과 배송 일정이 보이면 체험 문의로 이어질 수 있다.',goal:'서비스를 이해한 사람이 첫 체험 구독을 문의하도록 한다.',candidates:[{name:'가격 혜택 알리기',action:'할인 금액을 중심으로 첫 체험 안내',basis:'할인 예산 필요. 지속 가치 전달이 약할 수 있음.'},{name:'취향 선택 돕기',action:'취향별 원두 구성과 배송 일정을 한 페이지로 설명',basis:'구성 자료 필요. 가상 문제 가설과 직접 연결.'},{name:'실사용 후기 모으기',action:'동의받은 이용자의 후기 소개',basis:'실제 후기 자료가 없어 첫 실행은 보류.'}],selected:'1',reason:'제안 이유와 서비스 구성을 함께 설명할 수 있고 할인·후기 자료 없이도 작성 가능하다.',exclude:'유료 광고, 근거 없는 고객 후기',message:'어떤 원두를 고를지 고민될 때, 취향별 구성과 배송 일정을 먼저 확인하세요.',channel:'서비스 소개 페이지',action:'취향별 구성과 배송 일정 안내를 작성하고 체험 문의 버튼으로 연결한다.',metric:'체험 문의 건수',definition:'측정 기간에 실제 접수된 체험 문의. 중복 문의 제외.',source:'담당자가 확인한 문의 기록. 현재는 자료 미확인.',rule:'문의가 목표보다 적으면 구성·일정의 이해 여부부터 확인하고 안내를 수정한다.'})},
 {industry:'교육·문화',name:'주말 글쓰기 모임의 참여 안내',summary:'참여를 망설이는 사람에게, 무엇을 먼저 알려야 할까요?',build:()=>example({name:'주말 글쓰기 모임의 참여 안내',industry:'교육·문화',target:'글을 쓰고 싶지만 처음 모임에 참여하기 부담스러운 성인',problem:'시간·준비물·참여 수준이 명확하지 않아 신청을 망설일 수 있다.',importance:'참여 조건을 알지 못하면 내용에 관심이 있어도 다음 행동으로 이어지기 어렵다.',evidence:'가상 요청서 설정. 실제 문의나 참여 기록은 아직 없음.',assumption:'진행 방식과 첫 참여 준비를 설명하면 신청 부담이 줄어들 수 있다.',goal:'초보 참여자가 조건을 이해하고 첫 모임에 신청한다.',candidates:[{name:'진행 조건 명확히 알리기',action:'시간·준비물·초보 참여 가능 여부를 안내',basis:'운영자가 확정한 조건 자료 필요.'},{name:'완성 작품 보여주기',action:'동의받은 참여자 작품 소개',basis:'공개 동의와 작품 자료 필요.'},{name:'무료 체험 진행',action:'체험 회차 별도 운영',basis:'운영 시간과 장소 추가 필요.'}],selected:'0',reason:'추가 행사 없이 참여 조건을 명확히 하는 첫 실행을 할 수 있다.',exclude:'실제 동의 없는 작품 공개, 추가 회차 운영',message:'처음 쓰는 분도 준비할 수 있도록 시간과 준비물을 먼저 안내합니다.',channel:'모임 신청 페이지',action:'참여 조건을 한 페이지로 정리하고 일정 확인 후 신청하도록 안내한다.',metric:'완료 신청 건수',definition:'기간 내 신청 완료 건수. 취소·중복 제외.',source:'운영자가 확인한 신청 목록. 현재 미측정.',rule:'신청이 목표 미달이면 조건 이해와 신청 과정에서 막힌 지점을 먼저 조사한다.'})},
 {industry:'기업 서비스',name:'업무 도구의 상담 제안',summary:'기능 목록 대신, 고객이 해결할 문제를 설명해 봅니다.',build:()=>example({name:'업무 도구의 상담 제안',industry:'기업 서비스',target:'여러 사람의 승인 요청을 취합하는 소규모 팀 담당자',problem:'기능 이름만으로 현재 승인 업무에 어떤 도움이 되는지 이해하기 어렵다.',importance:'자신의 업무와 관련성을 이해하지 못하면 상담을 요청할 이유가 부족하다.',evidence:'가상 서비스 설명을 바탕으로 작성. 실제 시간 절감 자료나 고객 반응 없음.',assumption:'승인 요청이 들어오는 상황부터 설명하면 관련성을 판단하기 쉬워질 수 있다.',goal:'관련 업무를 가진 담당자가 적합성을 확인하는 상담을 요청한다.',candidates:[{name:'기능 목록 소개',action:'주요 기능과 요금 안내',basis:'서비스 정보 필요. 업무 맥락 전달은 제한적.'},{name:'문제 상황 중심 설명',action:'승인 요청의 입력·취합·확인 흐름으로 소개',basis:'검증되지 않은 절감 수치는 사용하지 않음.'},{name:'무료 도입 제안',action:'시험 사용 계정 제공',basis:'계정과 운영 지원 필요.'}],selected:'1',reason:'실제 효과를 주장하지 않으면서 업무 상황과 기능의 연결을 설명할 수 있다.',exclude:'시간 절감 수치 주장, 자동 계정 제공',message:'승인 요청을 취합하는 흐름에 맞는지, 현재 업무를 기준으로 확인해 보세요.',channel:'서비스 상담 소개 페이지',action:'승인 업무 상황별 기능 연결을 작성하고 현재 업무를 설명하는 상담을 요청한다.',metric:'적합한 상담 요청 수',definition:'승인 취합 업무가 있다고 확인된 상담 요청. 중복 제외.',source:'담당자가 확인한 상담 요청 기록. 실제 자료 없음.',rule:'요청은 많지만 적합한 문의가 적으면 대상과 사용 조건을 더 분명히 설명한다.'})}
];
home();
if(loadError)$('#save-status').textContent='기존 자료 읽기 오류 · 원본 보존';else if(projects.length)$('#save-status').textContent='이 브라우저에 저장됨';
